
[env]
TERM = "xterm-256color"

[window]
decorations = "transparent"
padding = { x = 15, y = 20}

[cursor]
blink_interval = 500

[cursor.style]
shape = "Underline"
blinking = "Always"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
