[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
padding = { x = 15, y = 30 }
dimensions = { columns = 228, lines = 66 }

[cursor]
blink_interval = 500

[cursor.style]
shape = "Underline"
blinking = "Always"

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
