format = """
$username\
$hostname\
$git_branch\
$git_status\
$cmd_duration\
$python\
$line_break\
$directory\
$character"""

[directory]
format = '╰─ [in $path]($style)'
style = "white"

[character]
success_symbol = "[ \\$](bold green)"
error_symbol = "[ X](bold red)"
vimcmd_symbol = "[ \\$]](bold green)"

[git_branch]
format = "[on $branch]($style) "
style = "white"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](red)($ahead_behind$stashed)]($style)"
style = "green"
conflicted = "conf "
untracked = "untr "
modified = "modf "
staged = "stgd "
renamed = "rnmd "
deleted = "dltd "
stashed = "stsh "

# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"

[hostname]
ssh_only = false
format = '[$username](bold green)[$hostname](bold green) '
trim_at = '.local'
disabled = false

[username]
style_user = 'bold green'
style_root = 'red'
format = '╭─ [$user@]($style)'
disabled = false
show_always = true